#include "World.hpp"

TileSet World::tiles_ = {new tile::Border(0, 0),   new tile::Wall(1, 0),
                         new tile::Wall(2, 0),     new tile::Wall(3, 0),
                         new tile::Wall(4, 0),     new tile::Wall(5, 0),
                         new tile::Wall(6, 0),     new tile::Wall(7, 0),
                         new tile::Wall(8, 0),     new tile::Wall(9, 0),
                         new tile::Wall(10, 0),    new tile::Wall(11, 0),
                         new tile::Wall(12, 0),    new tile::Wall(13, 0),
                         new tile::Wall(14, 0),    new tile::Wall(15, 0),
                         new tile::Wall(16, 0),    new tile::Wall(17, 0),
                         new tile::Wall(18, 0),    new tile::Wall(19, 0),
                         new tile::Border(20, 0),  new tile::Border(0, 1),
                         new tile::Wall(1, 1),     new tile::Dot(2, 1),
                         new tile::Dot(3, 1),      new tile::Dot(4, 1),
                         new tile::Dot(5, 1),      new tile::Dot(6, 1),
                         new tile::Dot(7, 1),      new tile::Dot(8, 1),
                         new tile::Dot(9, 1),      new tile::Wall(10, 1),
                         new tile::Dot(11, 1),     new tile::Dot(12, 1),
                         new tile::Dot(13, 1),     new tile::Dot(14, 1),
                         new tile::Dot(15, 1),     new tile::Dot(16, 1),
                         new tile::Dot(17, 1),     new tile::Dot(18, 1),
                         new tile::Wall(19, 1),    new tile::Border(20, 1),
                         new tile::Border(0, 2),   new tile::Wall(1, 2),
                         new tile::Pellet(2, 2),   new tile::Wall(3, 2),
                         new tile::Wall(4, 2),     new tile::Dot(5, 2),
                         new tile::Wall(6, 2),     new tile::Wall(7, 2),
                         new tile::Wall(8, 2),     new tile::Dot(9, 2),
                         new tile::Wall(10, 2),    new tile::Dot(11, 2),
                         new tile::Wall(12, 2),    new tile::Wall(13, 2),
                         new tile::Wall(14, 2),    new tile::Dot(15, 2),
                         new tile::Wall(16, 2),    new tile::Wall(17, 2),
                         new tile::Pellet(18, 2),  new tile::Wall(19, 2),
                         new tile::Border(20, 2),  new tile::Border(0, 3),
                         new tile::Wall(1, 3),     new tile::Dot(2, 3),
                         new tile::Dot(3, 3),      new tile::Dot(4, 3),
                         new tile::Dot(5, 3),      new tile::Dot(6, 3),
                         new tile::Dot(7, 3),      new tile::Dot(8, 3),
                         new tile::Dot(9, 3),      new tile::Dot(10, 3),
                         new tile::Dot(11, 3),     new tile::Dot(12, 3),
                         new tile::Dot(13, 3),     new tile::Dot(14, 3),
                         new tile::Dot(15, 3),     new tile::Dot(16, 3),
                         new tile::Dot(17, 3),     new tile::Dot(18, 3),
                         new tile::Wall(19, 3),    new tile::Border(20, 3),
                         new tile::Border(0, 4),   new tile::Wall(1, 4),
                         new tile::Dot(2, 4),      new tile::Wall(3, 4),
                         new tile::Wall(4, 4),     new tile::Dot(5, 4),
                         new tile::Wall(6, 4),     new tile::Dot(7, 4),
                         new tile::Wall(8, 4),     new tile::Wall(9, 4),
                         new tile::Wall(10, 4),    new tile::Wall(11, 4),
                         new tile::Wall(12, 4),    new tile::Dot(13, 4),
                         new tile::Wall(14, 4),    new tile::Dot(15, 4),
                         new tile::Wall(16, 4),    new tile::Wall(17, 4),
                         new tile::Dot(18, 4),     new tile::Wall(19, 4),
                         new tile::Border(20, 4),  new tile::Border(0, 5),
                         new tile::Wall(1, 5),     new tile::Dot(2, 5),
                         new tile::Dot(3, 5),      new tile::Dot(4, 5),
                         new tile::Dot(5, 5),      new tile::Wall(6, 5),
                         new tile::Dot(7, 5),      new tile::Dot(8, 5),
                         new tile::Dot(9, 5),      new tile::Wall(10, 5),
                         new tile::Dot(11, 5),     new tile::Dot(12, 5),
                         new tile::Dot(13, 5),     new tile::Wall(14, 5),
                         new tile::Dot(15, 5),     new tile::Dot(16, 5),
                         new tile::Dot(17, 5),     new tile::Dot(18, 5),
                         new tile::Wall(19, 5),    new tile::Border(20, 5),
                         new tile::Border(0, 6),   new tile::Wall(1, 6),
                         new tile::Wall(2, 6),     new tile::Wall(3, 6),
                         new tile::Wall(4, 6),     new tile::Dot(5, 6),
                         new tile::Wall(6, 6),     new tile::Wall(7, 6),
                         new tile::Wall(8, 6),     new tile::Empty(9, 6),
                         new tile::Wall(10, 6),    new tile::Empty(11, 6),
                         new tile::Wall(12, 6),    new tile::Wall(13, 6),
                         new tile::Wall(14, 6),    new tile::Dot(15, 6),
                         new tile::Wall(16, 6),    new tile::Wall(17, 6),
                         new tile::Wall(18, 6),    new tile::Wall(19, 6),
                         new tile::Border(20, 6),  new tile::Border(0, 7),
                         new tile::Border(1, 7),   new tile::Border(2, 7),
                         new tile::Border(3, 7),   new tile::Wall(4, 7),
                         new tile::Dot(5, 7),      new tile::Wall(6, 7),
                         new tile::Empty(7, 7),    new tile::Empty(8, 7),
                         new tile::Empty(9, 7),    new tile::Empty(10, 7),
                         new tile::Empty(11, 7),   new tile::Empty(12, 7),
                         new tile::Empty(13, 7),   new tile::Wall(14, 7),
                         new tile::Dot(15, 7),     new tile::Wall(16, 7),
                         new tile::Border(17, 7),  new tile::Border(18, 7),
                         new tile::Border(19, 7),  new tile::Border(20, 7),
                         new tile::Wall(0, 8),     new tile::Wall(1, 8),
                         new tile::Wall(2, 8),     new tile::Wall(3, 8),
                         new tile::Wall(4, 8),     new tile::Dot(5, 8),
                         new tile::Wall(6, 8),     new tile::Empty(7, 8),
                         new tile::Wall(8, 8),     new tile::Wall(9, 8),
                         new tile::Door(10, 8),    new tile::Wall(11, 8),
                         new tile::Wall(12, 8),    new tile::Empty(13, 8),
                         new tile::Wall(14, 8),    new tile::Dot(15, 8),
                         new tile::Wall(16, 8),    new tile::Wall(17, 8),
                         new tile::Wall(18, 8),    new tile::Wall(19, 8),
                         new tile::Wall(20, 8),    new tile::Empty(0, 9),
                         new tile::Empty(1, 9),    new tile::Empty(2, 9),
                         new tile::Empty(3, 9),    new tile::Empty(4, 9),
                         new tile::Dot(5, 9),      new tile::Empty(6, 9),
                         new tile::Empty(7, 9),    new tile::Wall(8, 9),
                         new tile::Empty(9, 9),    new tile::Empty(10, 9),
                         new tile::Empty(11, 9),   new tile::Wall(12, 9),
                         new tile::Empty(13, 9),   new tile::Empty(14, 9),
                         new tile::Dot(15, 9),     new tile::Empty(16, 9),
                         new tile::Empty(17, 9),   new tile::Empty(18, 9),
                         new tile::Empty(19, 9),   new tile::Empty(20, 9),
                         new tile::Wall(0, 10),    new tile::Wall(1, 10),
                         new tile::Wall(2, 10),    new tile::Wall(3, 10),
                         new tile::Wall(4, 10),    new tile::Dot(5, 10),
                         new tile::Wall(6, 10),    new tile::Empty(7, 10),
                         new tile::Wall(8, 10),    new tile::Wall(9, 10),
                         new tile::Wall(10, 10),   new tile::Wall(11, 10),
                         new tile::Wall(12, 10),   new tile::Empty(13, 10),
                         new tile::Wall(14, 10),   new tile::Dot(15, 10),
                         new tile::Wall(16, 10),   new tile::Wall(17, 10),
                         new tile::Wall(18, 10),   new tile::Wall(19, 10),
                         new tile::Wall(20, 10),   new tile::Border(0, 11),
                         new tile::Border(1, 11),  new tile::Border(2, 11),
                         new tile::Border(3, 11),  new tile::Wall(4, 11),
                         new tile::Dot(5, 11),     new tile::Wall(6, 11),
                         new tile::Empty(7, 11),   new tile::Empty(8, 11),
                         new tile::Empty(9, 11),   new tile::Empty(10, 11),
                         new tile::Empty(11, 11),  new tile::Empty(12, 11),
                         new tile::Empty(13, 11),  new tile::Wall(14, 11),
                         new tile::Dot(15, 11),    new tile::Wall(16, 11),
                         new tile::Border(17, 11), new tile::Border(18, 11),
                         new tile::Border(19, 11), new tile::Border(20, 11),
                         new tile::Border(0, 12),  new tile::Wall(1, 12),
                         new tile::Wall(2, 12),    new tile::Wall(3, 12),
                         new tile::Wall(4, 12),    new tile::Dot(5, 12),
                         new tile::Wall(6, 12),    new tile::Empty(7, 12),
                         new tile::Wall(8, 12),    new tile::Wall(9, 12),
                         new tile::Wall(10, 12),   new tile::Wall(11, 12),
                         new tile::Wall(12, 12),   new tile::Empty(13, 12),
                         new tile::Wall(14, 12),   new tile::Dot(15, 12),
                         new tile::Wall(16, 12),   new tile::Wall(17, 12),
                         new tile::Wall(18, 12),   new tile::Wall(19, 12),
                         new tile::Border(20, 12), new tile::Border(0, 13),
                         new tile::Wall(1, 13),    new tile::Dot(2, 13),
                         new tile::Dot(3, 13),     new tile::Dot(4, 13),
                         new tile::Dot(5, 13),     new tile::Dot(6, 13),
                         new tile::Dot(7, 13),     new tile::Dot(8, 13),
                         new tile::Dot(9, 13),     new tile::Wall(10, 13),
                         new tile::Dot(11, 13),    new tile::Dot(12, 13),
                         new tile::Dot(13, 13),    new tile::Dot(14, 13),
                         new tile::Dot(15, 13),    new tile::Dot(16, 13),
                         new tile::Dot(17, 13),    new tile::Dot(18, 13),
                         new tile::Wall(19, 13),   new tile::Border(20, 13),
                         new tile::Border(0, 14),  new tile::Wall(1, 14),
                         new tile::Dot(2, 14),     new tile::Wall(3, 14),
                         new tile::Wall(4, 14),    new tile::Dot(5, 14),
                         new tile::Wall(6, 14),    new tile::Wall(7, 14),
                         new tile::Wall(8, 14),    new tile::Dot(9, 14),
                         new tile::Wall(10, 14),   new tile::Dot(11, 14),
                         new tile::Wall(12, 14),   new tile::Wall(13, 14),
                         new tile::Wall(14, 14),   new tile::Dot(15, 14),
                         new tile::Wall(16, 14),   new tile::Wall(17, 14),
                         new tile::Dot(18, 14),    new tile::Wall(19, 14),
                         new tile::Border(20, 14), new tile::Border(0, 15),
                         new tile::Wall(1, 15),    new tile::Pellet(2, 15),
                         new tile::Dot(3, 15),     new tile::Wall(4, 15),
                         new tile::Dot(5, 15),     new tile::Dot(6, 15),
                         new tile::Dot(7, 15),     new tile::Dot(8, 15),
                         new tile::Dot(9, 15),     new tile::Empty(10, 15),
                         new tile::Dot(11, 15),    new tile::Dot(12, 15),
                         new tile::Dot(13, 15),    new tile::Dot(14, 15),
                         new tile::Dot(15, 15),    new tile::Wall(16, 15),
                         new tile::Dot(17, 15),    new tile::Pellet(18, 15),
                         new tile::Wall(19, 15),   new tile::Border(20, 15),
                         new tile::Border(0, 16),  new tile::Wall(1, 16),
                         new tile::Wall(2, 16),    new tile::Dot(3, 16),
                         new tile::Wall(4, 16),    new tile::Dot(5, 16),
                         new tile::Wall(6, 16),    new tile::Dot(7, 16),
                         new tile::Wall(8, 16),    new tile::Wall(9, 16),
                         new tile::Wall(10, 16),   new tile::Wall(11, 16),
                         new tile::Wall(12, 16),   new tile::Dot(13, 16),
                         new tile::Wall(14, 16),   new tile::Dot(15, 16),
                         new tile::Wall(16, 16),   new tile::Dot(17, 16),
                         new tile::Wall(18, 16),   new tile::Wall(19, 16),
                         new tile::Border(20, 16), new tile::Border(0, 17),
                         new tile::Wall(1, 17),    new tile::Dot(2, 17),
                         new tile::Dot(3, 17),     new tile::Dot(4, 17),
                         new tile::Dot(5, 17),     new tile::Wall(6, 17),
                         new tile::Dot(7, 17),     new tile::Dot(8, 17),
                         new tile::Dot(9, 17),     new tile::Wall(10, 17),
                         new tile::Dot(11, 17),    new tile::Dot(12, 17),
                         new tile::Dot(13, 17),    new tile::Wall(14, 17),
                         new tile::Dot(15, 17),    new tile::Dot(16, 17),
                         new tile::Dot(17, 17),    new tile::Dot(18, 17),
                         new tile::Wall(19, 17),   new tile::Border(20, 17),
                         new tile::Border(0, 18),  new tile::Wall(1, 18),
                         new tile::Dot(2, 18),     new tile::Wall(3, 18),
                         new tile::Wall(4, 18),    new tile::Wall(5, 18),
                         new tile::Wall(6, 18),    new tile::Wall(7, 18),
                         new tile::Wall(8, 18),    new tile::Dot(9, 18),
                         new tile::Wall(10, 18),   new tile::Dot(11, 18),
                         new tile::Wall(12, 18),   new tile::Wall(13, 18),
                         new tile::Wall(14, 18),   new tile::Wall(15, 18),
                         new tile::Wall(16, 18),   new tile::Wall(17, 18),
                         new tile::Dot(18, 18),    new tile::Wall(19, 18),
                         new tile::Border(20, 18), new tile::Border(0, 19),
                         new tile::Wall(1, 19),    new tile::Dot(2, 19),
                         new tile::Dot(3, 19),     new tile::Dot(4, 19),
                         new tile::Dot(5, 19),     new tile::Dot(6, 19),
                         new tile::Dot(7, 19),     new tile::Dot(8, 19),
                         new tile::Dot(9, 19),     new tile::Dot(10, 19),
                         new tile::Dot(11, 19),    new tile::Dot(12, 19),
                         new tile::Dot(13, 19),    new tile::Dot(14, 19),
                         new tile::Dot(15, 19),    new tile::Dot(16, 19),
                         new tile::Dot(17, 19),    new tile::Dot(18, 19),
                         new tile::Wall(19, 19),   new tile::Border(20, 19),
                         new tile::Border(0, 20),  new tile::Wall(1, 20),
                         new tile::Wall(2, 20),    new tile::Wall(3, 20),
                         new tile::Wall(4, 20),    new tile::Wall(5, 20),
                         new tile::Wall(6, 20),    new tile::Wall(7, 20),
                         new tile::Wall(8, 20),    new tile::Wall(9, 20),
                         new tile::Wall(10, 20),   new tile::Wall(11, 20),
                         new tile::Wall(12, 20),   new tile::Wall(13, 20),
                         new tile::Wall(14, 20),   new tile::Wall(15, 20),
                         new tile::Wall(16, 20),   new tile::Wall(17, 20),
                         new tile::Wall(18, 20),   new tile::Wall(19, 20),
                         new tile::Border(20, 20)};

World::World() {}

World::~World() {}

void World::Update() {}

void World::Render(sf::RenderWindow &render_window) {
  for (auto &tile : World::tiles_) {
    tile->Render(render_window);
  }
}

tile::Tile *World::FindTile(const sf::Vector2u position) {
  auto tile = std::find_if(
      World::tiles_.begin(), World::tiles_.end(),
      [position](tile::Tile *tile) { return tile->GetPosition() == position; });
  if (tile == World::tiles_.end()) {
    return NULL;
  }
  return *tile;
}
